FROM alpine

RUN apk update && apk add mosquitto
RUN apk add mosquitto-clients
RUN apk add git
RUN apk add python3 py3-pip
RUN pip3 install paho-mqtt

WORKDIR /
RUN git clone https://github.com/mt467/w251-hw3.git
WORKDIR /w251-hw3

RUN git pull origin master
