FROM ubuntu

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    python3-pip \
    python3-setuptools \
    python3-dev \
    python3-numpy \
    python3-opencv \
    python-opencv  \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install paho-mqtt

WORKDIR /
RUN git clone https://github.com/mt467/w251-hw3.git
WORKDIR /w251-hw3

RUN git pull origin master
